### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by Rand-Random** [bigretromike/nakamoriplugin#13]
I am getting an exception with the following log (upon starting the addon).

21:02:02 T:2808  NOTICE: Thread LanguageInvoker start, auto delete: false
21:02:02 T:2808  NOTICE: -->Python Interpreter Initialized<--
21:02:02 T:2808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\nakamoriplugin-master\nakamori.py", line 172, in <module>
                                                buildMainMenu()
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\nakamoriplugin-master\nakamori.py", line 35, in buildMainMenu
                                                e=xml.etree.ElementTree.XML(getHtml(www,params2))
                                              File "C:\Users\XXX\AppData\Roaming\Kodi\addons\nakamoriplugin-master\nakamori.py", line 143, in getHtml
                                                response = urlopen(req, timeout=60)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 404: Not Found
                                            -->End of Python script error report<--
21:02:02 T:17892   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.nakamoriplugin/
21:02:02 T:17892   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nakamoriplugin/) failed
21:02:02 T:16048  NOTICE: Thread BackgroundLoader start, auto delete: false

I checked the addon Settings (IP/Port and User) but nothing wrong there Default Settings are just fine.

**Comment by bigretromike** [comment]
You need the JMMserver with Kodi support - download repo and compile.
Or please wait few days till new version of jmm is released.
